### ISSUE TITLE
Still active ?

### ISSUE THREAD

**Issue by sebastienleon** [Piwigo/Piwigo-Embedded-Videos#12]
Hello,

This plugin seems pretty cool, according the description, and I saw it was not maintained, but I am a bit puzzled...
I am very new to Piwigo (installed first on my LAMP yesterday) and I am not sure to understand everything...
This plugin seems to be compatible with Piwigo version 2.4... which is ~9 years old. Right ?
Is it not compatible with nowadays version (v 11) ? (despite I see some new version of this plugin few weeks ago !?)

There is also zero instructions to install (and this plugin doesn't shows up in the list of available plugins of my Piwigo). Shall I simply put it in the plugin directory ?
(I did that, but nothing changed in the interface of Piwigo, and now I get a warning icon saying it may not be compatible with my version...)

In case this plugin is no longer compatible with Piwigo, is there anything around that could do the same ?

Thanks for clarifications & thank you for your code :-)

Sébastien

**Comment by sebastienleon** [comment]
I reply to myself to some of my question, as it could be useful for another Piwigo newbie like me:
- this plugin seems to be compatible with last version of Piwigo (v 11 early days of 2021)
- to install it, you just need to decompress it in /plugins directory
- it works great ! To add a new entry, click on the "Configure" button on this plugin in Piwigo plugin list.
I still do not know if it is safe to ignore the warning... And why it is not available in Piwigo available plugin list... (could be great for users who are not root)
Thanks !

**Comment by mistic100** [comment]
It's not available on v11 because I didn't test it (hence the "not maintained") so I didn't not marked it compatible on https://piwigo.org/ext/extension_view.php?eid=136
