### ISSUE TITLE
Embedded Videos don't work becaus many warning shown in config page

### ISSUE THREAD

**Issue by ericbay9** [Piwigo/Piwigo-Embedded-Videos#18]
Hello,

I have this issue with the plugin Embedded Videos
![image](https://user-images.githubusercontent.com/122172279/211163037-4c263830-9603-42a0-b764-dac031c00969.png)

piwigo : 13.4.0 
![image](https://user-images.githubusercontent.com/122172279/211163070-672e8dba-b8f8-4d27-8b00-43ecea46b2b0.png)
![image](https://user-images.githubusercontent.com/122172279/211163099-2e78a92f-5e76-4ea1-b24d-512899035d96.png)

Can you help me because i have youtube video to link to my piwigo website

Eric

**Comment by Dechinta** [comment]
I have exactly the same issues.

**Comment by lvdlaar** [comment]
Add this line to your \local\config\config.inc.php
$conf['show_php_errors'] = E_ALL ^ E_DEPRECATED ^ E_WARNING;

That should do the trick.

See also https://piwigo.org/forum/viewtopic.php?pid=180778#p180778 for a generally better approach to log error messages instead of displaying them.

**Comment by ericbay9** [comment]
> Add this line to your \local\config\config.inc.php 

I don't find this file

in directory /local/config
i have only 2 files
![image](https://github.com/Piwigo/Piwigo-Embedded-Videos/assets/122172279/f61c63de-8dd8-48f7-9d03-daaea249f65a)

**Comment by lvdlaar** [comment]
> > Add this line to your \local\config\config.inc.php
> 
> I don't find this file
> 
> in directory /local/config i have only 2 files ![image](https://user-images.githubusercontent.com/122172279/279177317-f61c63de-8dd8-48f7-9d03-daaea249f65a.png)

You can add the file manually then, mine has this content:

```
<?php
$conf['show_exif'] = false;
$conf['use_exif'] = false;
$conf['show_php_errors'] = E_ALL ^ E_DEPRECATED ^ E_WARNING;
?>
```

**Comment by ericbay9** [comment]
it's working
thanks you
